//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSwap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class FASE
    {
        public FASE()
        {
            this.TAREFA = new HashSet<TAREFA>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FASEID { get; set; }
        public string PROJETOID { get; set; }
        public string DESCRICAO { get; set; }
        public DateTime? INICIOREAL { get; set; }
        public DateTime? FIMREAL { get; set; }
        public DateTime? INICIOBASE { get; set; }
        public DateTime? FIMBASE { get; set; }
        public double? DURACAO { get; set; }
    
        public virtual PROJETO PROJETO { get; set; }
        public virtual ICollection<TAREFA> TAREFA { get; set; }
    }
}
