//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSwap.Models
{
    using System.Collections.Generic;

    public partial class HABILIDADE
    {
        public HABILIDADE()
        {
            this.RECURSOHABILIDADE = new HashSet<RECURSOHABILIDADE>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<RECURSOHABILIDADE> RECURSOHABILIDADE { get; set; }
    }
}
