//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSwap.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PROJETO
    {
        public PROJETO()
        {
            this.FASE = new HashSet<FASE>();
        }
    
        [Key]
        public string CODIGO { get; set; }
        public string NOME { get; set; }
        public string GERENTEID { get; set; }
        public string CAMINHO { get; set; }
    
        public virtual ICollection<FASE> FASE { get; set; }
        public virtual RECURSO RECURSO { get; set; }
    }
}
