//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSwap.Models
{
    using Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class RECURSOTAREFA
    {
        public RECURSOTAREFA()
        {
            this.RecursoTarefaExecutados = new HashSet<RecursoTarefaExecutado>();
        }
    
        [Key]
        [Column(Order = 1)]
        public string RECURSOID { get; set; }
        [Key]
        [Column(Order = 2)]
        public string TAREFAID { get; set; }
        public int FASEID { get; set; }
        public string PROJETOID { get; set; }
        public DateTime DATAINICIO { get; set; }
        public DateTime? DATAFIM { get; set; }
        public int? STATUS { get; set; }
    
        public virtual RECURSO RECURSO { get; set; }
        public virtual TAREFA TAREFA { get; set; }
        public virtual ICollection<RecursoTarefaExecutado> RecursoTarefaExecutados { get; set; }
    }
}
