//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSwap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREFA
    {
        public TAREFA()
        {
            this.RECURSOTAREFA = new HashSet<RECURSOTAREFA>();
        }
    
        public string PROJETOID { get; set; }
        public int FASEID { get; set; }
        public string TAREFAID { get; set; }
        public string DESCRICAO { get; set; }
        public int? TIPO { get; set; }
        public int? LINHA { get; set; }
        public int? LINHADEP { get; set; }
        public double? DURACAO { get; set; }
        public DateTime? INICIOREAL { get; set; }
        public DateTime? FIMREAL { get; set; }
        public DateTime? INICIOBASE { get; set; }
        public DateTime? FIMBASE { get; set; }
        public double? PORCENTAGEM { get; set; }
    
        public virtual FASE FASE { get; set; }
        public virtual ICollection<RECURSOTAREFA> RECURSOTAREFA { get; set; }
    }
}
